# Generated by Django 5.2 on 2025-07-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_post_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
